languageCode = 'en-us'
theme = 'beautifulhugo'

baseurl = "https://example.com/"
title = "Blog"

[Params]
  subtitle = "My personal blog and projects"
  mainSections = ["blog", "projects"]
  logo = "/img/avatar-icon.png"
  favicon = "/img/favicon.ico"
  dateFormat = "2 January 2006"
  colorScheme = "auto"
  readingTime = true
  rss = true

  [Params.search]
    provider = "fuse"

[[menu.main]]
    name = "Blog"
    url = "blog/"
    weight = 1

[[menu.main]]
    name = "Projects"
    url = "projects/"
    weight = 2

[[menu.main]]
    name = "Tags"
    url = "tags/"
    weight = 3

[Params.author]
  name = "Nico Rudolph"
  website = "yourwebsite.com"
  email = "youremail@domain.com"
  github = "Rextorne"

[markup.highlight]
  noClasses = false

[markup.goldmark.parser.attribute]
  block = true

[markup.goldmark.renderer]
  unsafe = true
